//
// Created by GDL on 19/4/18.
//

#ifndef SOA_RAGNAROK_EXITCODES_H
#define SOA_RAGNAROK_EXITCODES_H

#define FAILED_TO_ASSERT_PARAMS     0x01
#define INVALID_COMMAND             0x02
#define VOLUME_DOES_NOT_EXIST       0x03
#define NOT_ENOUGH_PRIVILEGES       0x04
#define CANNOT_OPEN_FD_TO_VOLUME    0x05
#define FILE_SYSTEM_NOT_SUPPORTED   0x06
#define CANNOT_ASSERT_FILESYSTEM    0x07


#endif //SOA_RAGNAROK_EXITCODES_H
